2025-06-05 10:43:03,357 INFO: Response status for citi-custom-cash: 200 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:638]
2025-06-05 10:43:03,365 INFO: Successfully fetched data for citi-custom-cash [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:641]
2025-06-05 10:43:04,866 INFO: Fetching card details for us-bank-altitude-go [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:630]
2025-06-05 10:43:04,868 INFO: Fetching card details for chase-freedom-flex [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:630]
2025-06-05 10:43:05,408 INFO: Response status for us-bank-altitude-go: 200 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:638]
2025-06-05 10:43:05,409 INFO: Successfully fetched data for us-bank-altitude-go [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:641]
2025-06-05 10:43:05,410 INFO: Response status for chase-freedom-flex: 200 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:638]
2025-06-05 10:43:05,410 INFO: Successfully fetched data for chase-freedom-flex [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:641]
2025-06-05 10:43:06,912 INFO: Fetching card details for ink-business-preferred [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:630]
2025-06-05 10:43:06,914 INFO: Fetching card details for amex-delta-reserve [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:630]
2025-06-05 10:43:07,456 INFO: Response status for amex-delta-reserve: 200 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:638]
2025-06-05 10:43:07,456 INFO: Successfully fetched data for amex-delta-reserve [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:641]
2025-06-05 10:43:07,458 INFO: Response status for ink-business-preferred: 200 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:638]
2025-06-05 10:43:07,458 INFO: Successfully fetched data for ink-business-preferred [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:641]
2025-06-05 10:43:08,959 INFO: Fetching card details for amex-hilton-aspire [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:630]
2025-06-05 10:43:08,961 INFO: Fetching card details for capital-one-spark-cash-plus [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:630]
2025-06-05 10:43:09,447 INFO: Response status for capital-one-spark-cash-plus: 200 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:638]
2025-06-05 10:43:09,448 INFO: Successfully fetched data for capital-one-spark-cash-plus [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:641]
2025-06-05 10:43:09,449 INFO: Response status for amex-hilton-aspire: 200 [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:638]
2025-06-05 10:43:09,449 INFO: Successfully fetched data for amex-hilton-aspire [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:641]
2025-06-05 10:57:42,671 INFO: Application startup [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:334]
2025-06-05 10:57:42,703 INFO: Starting Hypercorn server... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:832]
2025-06-05 11:11:18,505 INFO: Application startup [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:339]
2025-06-05 11:11:18,538 INFO: Starting Hypercorn server... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:924]
2025-06-05 11:12:17,990 ERROR: Exception on /auth/register [POST] [in /Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 254, in __call__
    return call_result.result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/asgiref/sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/Users/jonathanhyatt/dinero/dinero-backend/app.py", line 370, in register
    data = await request.get_json()
TypeError: object dict can't be used in 'await' expression
2025-06-05 11:15:36,433 INFO: Application startup [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:339]
2025-06-05 11:15:36,464 INFO: Starting Hypercorn server... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:924]
2025-06-05 11:19:21,866 INFO: Application startup [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:339]
2025-06-05 11:19:21,896 INFO: Starting Hypercorn server... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:924]
2025-06-05 11:21:29,202 ERROR: Exception on /auth/register [POST] [in /Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/jonathanhyatt/dinero/dinero-backend/app.py", line 378, in register
    if email in users:
NameError: name 'users' is not defined
2025-06-05 11:23:07,417 INFO: Application startup [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:339]
2025-06-05 11:23:07,446 INFO: Starting Hypercorn server... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:924]
2025-06-05 11:23:30,335 ERROR: Exception on /auth/register [POST] [in /Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/jonathanhyatt/dinero/dinero-backend/app.py", line 378, in register
    if email in users:
NameError: name 'users' is not defined
2025-06-05 13:12:23,711 INFO: Application startup [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:339]
2025-06-05 13:12:23,743 INFO: Starting Hypercorn server... [in /Users/jonathanhyatt/dinero/dinero-backend/app.py:924]
2025-06-05 13:14:43,872 ERROR: Exception on /auth/register [POST] [in /Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jonathanhyatt/dinero/.venv/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/jonathanhyatt/dinero/dinero-backend/app.py", line 378, in register
    if not name or not email or not password:
NameError: name 'users' is not defined
